### ISSUE TITLE
Chrome issue: flares do not line up after panning the map

### ISSUE THREAD

**Issue by DOOMitru** [nickcam/FlareClusterLayer#15] opened 2016-11-02 19:54 UTC
Hi Nick, 

We noticed an issue with the FCL v3 while using it in Chrome.  If you pan the map and then hover over a cluster, the flares tend to show up around the clusters previous position instead of it's new position. The flares position does get reset to the new position though if the zoom level changes.  I used the [plnkr](https://plnkr.co/edit/9o5CFWuYfUpgRBpLbO2z) you've made for me before to take a few screenshots to illustrate the issue.

Normal flare position: 
![Normal Position](http://i.imgur.com/wG4fb5n.png)

After panning to the left: 
![Panning Left](http://i.imgur.com/9vlGXwa.png)

After panning to the right: 
![Panning Right](http://i.imgur.com/6RFU6wK.png)

Not sure if you were aware of this or not.
Cheers,
Dumitru

**Comment by nickcam** [comment] 2016-11-02 21:40
Hi @DOOMitru,, yeah I noticed that happening in the plunker, but thought it was limited to there - something to do with how the plunker preview is rendered and offsets being calculated incorrectly based on it. 

If I go to the example page [http://flareclusterlayer.azurewebsites.net/index_v3.html](http://flareclusterlayer.azurewebsites.net/index_v3.html) it works fine for me...do you still see the issue in the example page? If so what version of Chrome are you using?

**Comment by DOOMitru** [comment] 2016-11-02 21:52
Hmm.. it doesn't appear to be happening on the example page but it is happening in our app in the exact same way as it happens in the plunker example.  I'm using Chrome version 54 (54.0.2840.87).  It doesn't seem to happen in FF or Edge though.

**Comment by nickcam** [comment] 2016-11-02 22:08
Hmm...ok. Does your map take up the full page, or is it only part of the page? Can you attach a zipped cut down version of the html/js you use to load it up? Will take a look when I get a chance.

**Comment by DOOMitru** [comment] 2016-11-02 22:45
Before we integrated the FCL into our app, we first made a simple mock up to see if it fit our needs.  I've included a stripped down version of that mock up which exhibits the problem.  Hopefully you can track it down. [Link to github repo](https://github.com/DOOMitru/arcgis)

**Comment by nickcam** [comment] 2016-11-02 22:54
Ok cool - will take a look. Don't think I'll have a chance to this week though sorry. If you manage to find it and fix it feel free to raise a PR. Seems as though the issue is in the createFlares function where it checks for the offsets of the map container to the page.

**Comment by nickcam** [comment] 2016-11-04 11:43
Hi @DOOMitru, just pushed up a fix for this. Turns out it was only an issue with v3.18, which is why my example still worked as it was previously referencing 3.16.

As of 3.18 when the map is panned the surface (svg element) has some translate values added to the transform style property to cater for the panning of the map, previous versions didn't apply these translate values. Zooming would reset them to 0. Because of this the actual svg element moved so when positioning the flares they would be out of position, so just had to calc the translate values if they exist and then apply them to the positioning of the flares as well. It should work for lower versions and 3.18 now.

**Closed as completed by nickcam** 2016-11-04 11:43 UTC

**Comment by DOOMitru** [comment] 2016-11-04 15:39
Great! Thanks for taking the time to update it.  It's much appreciated.
